version: "2"
services:
    nginx:
        build: ./nginx
        depends_on:
            - featureserver1
            - featureserver2
        ports:
            - "80:80"
    featureserver1:
        build: ./featureserver
        depends_on:
            - postgis
        env_file:
            - .env
    featureserver2:
        build: ./featureserver
        depends_on:
            - postgis
        env_file:
            - .env
    postgis:
        image: mdillon/postgis
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD


#query:
#    image: postgres
#    links:
#        - postgis
#    stdin_open: true
#    tty: true
#    command: sh -c 'exec psql -h $${POSTGIS_1_PORT_5432_TCP_ADDR} -p $${POSTGIS_1_PORT_5432_TCP_PORT} -U postgres'
