version: "3"
nginx:
    build: ./nginx
    links:
        - featureserver1:featureserver1
        - featureserver2:featureserver2
    ports:
        - "80:80"
featureserver1:
    build: ./featureserver
    ports:
        - "8080"
    links:
        - postgis:postgis
featureserver2:
    build: ./featureserver
    ports:
        - "8080"
    links:
        - postgis:postgis
postgis:
    image: mdillon/postgis
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=mysecretpassword
    ports:
        - 5432:5432
#query:
#    image: postgres
#    links:
#        - postgis
#    stdin_open: true
#    tty: true
#    command: sh -c 'exec psql -h $${POSTGIS_1_PORT_5432_TCP_ADDR} -p $${POSTGIS_1_PORT_5432_TCP_PORT} -U postgres'
